#!/bin/sh
clear
if [ "$1" == "clean" ]; then
  rm -rf build
fi
if [ ! -d build ]; then
  mkdir build
fi
cd build
cmake .. && make
echo
echo "+++ Running program pointer_to_member"
echo
./pointer_to_member
echo
if [ ! -f ../compile_commands.json ]; then
  ln -s build/compile_commands.json ../compile_commands.json 
fi
