#!/bin/sh
clear
if [ "$1" == "clean" ]; then
  rm -rf build
  rm -rf compile_commands.json
  exit
fi
if [ ! -d build ]; then
  mkdir build
fi
cd build
cmake .. && make
echo
echo "+++ Running program copy_elision"
echo
./copy_elision
echo
if [ ! -f ../compile_commands.json ]; then
  ln -s build/compile_commands.json ../compile_commands.json 
fi

